# Generated by Django 5.0.7 on 2024-08-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='uploads/user_profile/default.jpg', upload_to='uploads/user_profile/'),
        ),
    ]
