# Generated by Django 5.0.7 on 2024-08-06 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0012_remove_sellers_product_remove_sellers_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('khalti_api_code', models.CharField(default='', max_length=150)),
                ('facebook', models.URLField(default='', max_length=250, null=True)),
                ('instagram', models.URLField(default='', max_length=250, null=True)),
                ('youtube', models.URLField(default='', max_length=250, null=True)),
                ('extra', models.URLField(default='', max_length=250, null=True)),
                ('products', models.ManyToManyField(related_name='sellers_list', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
