# Generated by Django 5.0.7 on 2024-08-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellers',
            name='extra',
            field=models.URLField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='facebook',
            field=models.URLField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='instagram',
            field=models.URLField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='youtube',
            field=models.URLField(blank=True, default='', max_length=250, null=True),
        ),
    ]
