# Generated by Django 5.0.7 on 2024-08-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_sellers_cit_num_sellers_citizenship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellers',
            name='cit_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='pan_number',
            field=models.IntegerField(default=0),
        ),
    ]
