# Generated by Django 5.0.7 on 2024-08-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_alter_sellers_cit_num_alter_sellers_pan_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellers',
            name='cit_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='pan_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
