# Generated by Django 5.0.7 on 2024-08-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_alter_sellers_cit_num_alter_sellers_pan_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellers',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
