# Generated by Django 5.0.7 on 2024-08-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_sellers'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellers',
            name='khalti_api_code',
            field=models.CharField(default='', max_length=150),
        ),
    ]
