# Generated by Django 5.0.7 on 2024-08-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_sellers_khalti_api_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellers',
            name='extra',
            field=models.URLField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='sellers',
            name='faacebook',
            field=models.URLField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='sellers',
            name='instagram',
            field=models.URLField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='sellers',
            name='youtube',
            field=models.URLField(default='', max_length=250),
        ),
    ]
