# Generated by Django 5.0.7 on 2024-08-06 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_sellers_extra_sellers_faacebook_sellers_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellers',
            name='faacebook',
        ),
        migrations.AddField(
            model_name='sellers',
            name='facebook',
            field=models.URLField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='extra',
            field=models.URLField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='instagram',
            field=models.URLField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='youtube',
            field=models.URLField(default='', max_length=250, null=True),
        ),
    ]
