# Generated by Django 5.0.7 on 2024-08-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_sellers_faacebook_sellers_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellers',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sellers',
            name='user',
        ),
    ]
