# Generated by Django 5.0.7 on 2024-08-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_sellers_product_remove_sellers_user'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sellers',
            field=models.ManyToManyField(related_name='products_list', to='sellers.sellers'),
        ),
        migrations.DeleteModel(
            name='Sellers',
        ),
    ]
