# Generated by Django 4.2.14 on 2024-08-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_sellers_delete_sellers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
