# Generated by Django 5.0.6 on 2024-08-22 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_on_sale_alter_product_sale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='products.category')),
            ],
            options={
                'verbose_name': 'Category Sale',
                'verbose_name_plural': 'Category Sales',
            },
        ),
    ]
